<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9324" started-at="2021-04-22T09:30:29Z" finished-at="2021-04-22T09:30:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9324" started-at="2021-04-22T09:30:29Z" finished-at="2021-04-22T09:30:38Z">
      <class name="com.cjc.mt.tests.Test">
        <test-method status="PASS" signature="openDriver()[pri:0, instance:com.cjc.mt.tests.Test@43ee72e6]" name="openDriver" is-config="true" duration-ms="7989" started-at="2021-04-22T09:30:21Z" finished-at="2021-04-22T09:30:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDriver -->
        <test-method status="FAIL" signature="openUrl()[pri:0, instance:com.cjc.mt.tests.Test@43ee72e6]" name="openUrl" is-config="true" duration-ms="9028" started-at="2021-04-22T09:30:29Z" finished-at="2021-04-22T09:30:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.cjc.mt.tests.Test.openUrl(Test.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUrl -->
        <test-method status="SKIP" signature="maximize()[pri:0, instance:com.cjc.mt.tests.Test@43ee72e6]" name="maximize" is-config="true" duration-ms="0" started-at="2021-04-22T09:30:38Z" finished-at="2021-04-22T09:30:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- maximize -->
        <test-method status="SKIP" signature="createCookies()[pri:0, instance:com.cjc.mt.tests.Test@43ee72e6]" name="createCookies" is-config="true" duration-ms="0" started-at="2021-04-22T09:30:38Z" finished-at="2021-04-22T09:30:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCookies -->
        <test-method status="SKIP" signature="registerTest()[pri:-1, instance:com.cjc.mt.tests.Test@43ee72e6]" name="registerTest" duration-ms="0" started-at="2021-04-22T09:30:38Z" finished-at="2021-04-22T09:30:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.cjc.mt.tests.Test.openUrl(Test.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="SKIP" signature="createCookies()[pri:0, instance:com.cjc.mt.tests.Test@43ee72e6]" name="createCookies" is-config="true" duration-ms="0" started-at="2021-04-22T09:30:38Z" finished-at="2021-04-22T09:30:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCookies -->
        <test-method status="SKIP" signature="loginTest()[pri:1, instance:com.cjc.mt.tests.Test@43ee72e6]" name="loginTest" duration-ms="0" started-at="2021-04-22T09:30:38Z" finished-at="2021-04-22T09:30:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.cjc.mt.tests.Test.openUrl(Test.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.cjc.mt.tests.Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
